const $=id=>document.getElementById(id),film=$('film'),song=$('song'),story=window.STORY;
let returnPlaying=false,soundOn=true,ended=false,toastTimer,audioPending=false;
film.muted=false;
function soundLabel(){$('sound').textContent=audioPending&&soundOn?'音樂已開 · 輕觸播放':soundOn?'聲音 開':'開啟聲音';$('sound').setAttribute('aria-pressed',String(soundOn));}
const fmt=t=>`${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`;
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3500)}
async function play(){song.pause();if(ended){ended=false;film.currentTime=0}try{film.muted=!soundOn;await film.play();audioPending=false;soundLabel();$('start').hidden=true}catch(e){if(e.name!=='AbortError'){audioPending=soundOn;soundLabel();$('loading').hidden=true;$('play').textContent='播放';$('play').setAttribute('aria-label','播放電影');$('start').hidden=false;$('start').textContent=soundOn?'輕觸開始電影（含音樂）':'輕觸開始電影'}}}
function pause(){film.pause();song.pause()}
function syncSong(){}
function seek(t){ended=false;film.currentTime=Math.max(0,Math.min(t,film.duration||story.duration));syncSong();render()}
function render(){const t=film.currentTime;$('time').textContent=fmt(t);$('progress').value=t;const sub=story.subtitles.find(s=>t>=s.start&&t<s.end);$('speaker').textContent=sub?.speaker||'';$('line').textContent=sub?.text||'';const c=story.chapters.findLastIndex(s=>t>=s);const ambient=['001','010','014','018','020'][Math.max(0,c)];if(!$('ambient').src.endsWith(ambient+'.webp'))$('ambient').src=`assets/${ambient}.webp`;document.querySelectorAll('[data-time]').forEach((b,i)=>{b.classList.toggle('active',i===c);if(i===c)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current')});}

film.addEventListener('timeupdate',render);film.addEventListener('seeking',()=>{song.pause();render()});film.addEventListener('seeked',syncSong);
film.addEventListener('play',()=>{$('play').textContent='暫停';$('play').setAttribute('aria-label','暫停電影');$('loading').hidden=true});film.addEventListener('pause',()=>{$('play').textContent='播放';$('play').setAttribute('aria-label','播放電影');song.pause()});film.addEventListener('waiting',()=>{$('loading').hidden=false;song.pause()});film.addEventListener('playing',()=>{$('loading').hidden=true;syncSong()});film.addEventListener('loadedmetadata',()=>{$('progress').max=film.duration;if(!$('birthday').open)play()});film.addEventListener('error',()=>{$('loading').hidden=true;$('start').hidden=false;$('start').textContent='影片未能載入，輕觸重試';toast('請確認素材資料夾完整，或重新整理網頁。')});film.addEventListener('ended',()=>{ended=true;$('play').textContent='重播';$('play').setAttribute('aria-label','重播電影')});
$('start').onclick=()=>{if(film.error)film.load();play()};$('play').onclick=()=>{film.paused?play():pause()};$('prev').onclick=()=>{const t=film.currentTime;const c=story.chapters.findLastIndex(s=>s<t-.5);seek(story.chapters[Math.max(0,c)])};$('next').onclick=()=>{const t=film.currentTime;seek(story.chapters.find(s=>s>t+.5)??story.duration-.1)};$('progress').oninput=e=>seek(Number(e.target.value));document.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>seek(Number(b.dataset.time)));
$('cc').onclick=()=>{const on=$('cc').getAttribute('aria-pressed')!=='true';$('cc').setAttribute('aria-pressed',on);$('cc').textContent=`字幕 ${on?'開':'關'}`;$('captions').classList.toggle('off',!on)};
$('sound').onclick=async()=>{if(audioPending&&soundOn){await play();return;}soundOn=!soundOn;audioPending=false;film.muted=!soundOn;soundLabel();if(soundOn&&film.paused&&!$('birthday').open)await play();};
document.addEventListener('click',e=>{if(audioPending&&soundOn&&!$('birthday').open&&!e.target.closest('#sound,#play,#start,#egg,a'))play();},{capture:true});
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.querySelector('.cinema').requestFullscreen)await document.querySelector('.cinema').requestFullscreen();else if(film.webkitEnterFullscreen)film.webkitEnterFullscreen();else toast('此瀏覽器不支援全螢幕，請橫向觀看。')}catch(e){toast('全螢幕無法啟用，請橫向觀看。')}};

function openGift(resume=!film.paused){returnPlaying=resume;pause();$('birthday').showModal();try{$('wish').value=localStorage.getItem('yiting-birthday-wish')||''}catch(e){}}
function closeGift(){song.pause();$('birthday').close();if(returnPlaying&&!ended)play()}
$('egg').onclick=()=>openGift();$('close').onclick=closeGift;$('resume').onclick=closeGift;$('birthday').addEventListener('cancel',e=>{e.preventDefault();closeGift()});$('saveWish').onclick=()=>{if(!$('wish').value.trim()){$('wishStatus').textContent='先寫下一個小小的願望吧。';$('wish').focus();return}try{localStorage.setItem('yiting-birthday-wish',$('wish').value);$('birthday').classList.add('wish-sealed');$('wishStatus').textContent='願望已留在妳的瀏覽器裡，作者不會知道內容。願妳被愛，也勇敢做自己。'}catch(e){$('wishStatus').textContent='作者不會收到妳的願望。此瀏覽器無法儲存，請先複製留念。'}};
const cards=[['銀虎','022','希望每一天，妳都能笑得像今晚一樣。'],['藝俊','card-0000(1)','讓每一首歌，陪妳走向更好的明天。'],['諾亞','card-0000(5)','願妳的夢，永遠有光照著。'],['斑比','card-0000(3)','把快樂留給自己，也把勇氣留給夢想。'],['河玟','card-0000(4)','累的時候也沒關係，我們一直都在。'],['PLAVE','card-0000(2)','五道星光，一起祝妳生日快樂。']];
cards.forEach(([name,img,text],i)=>{const b=document.createElement('button');b.className='photocard';b.setAttribute('aria-label',name+'小卡，翻面看祝福');b.setAttribute('aria-pressed','false');const front=document.createElement('span');front.className='card-front';const image=document.createElement('img');image.src=`assets/${img}.webp`;image.alt=name+'生日小卡';image.loading='lazy';const label=document.createElement('strong');label.textContent=name;front.append(image,label);const back=document.createElement('span');back.className='card-back';const star=document.createElement('span');star.textContent='✦';const words=document.createElement('span');words.textContent=text;back.append(star,words);b.append(front,back);b.onclick=()=>{const flipped=b.classList.toggle('flipped');b.setAttribute('aria-pressed',String(flipped));$('giftText').textContent=name+'｜'+text;};$('cards').append(b)});
$('bookSize').onclick=()=>{const enlarged=document.querySelector('.novel').classList.toggle('large-print');$('bookSize').textContent=enlarged?'標準字體':'放大字體';};
let lastSave=0;film.addEventListener('timeupdate',()=>{if(Math.abs(film.currentTime-lastSave)>1){lastSave=film.currentTime;try{localStorage.setItem('yiting-film-progress',String(film.currentTime));localStorage.setItem('yiting-last-mode','movie');}catch{}}});
if(new URLSearchParams(location.search).get('resume')==='1')film.addEventListener('loadedmetadata',()=>{try{const saved=Number(localStorage.getItem('yiting-film-progress'));if(Number.isFinite(saved)&&saved>0&&saved<story.duration-1)seek(saved);}catch{}},{once:true});
document.addEventListener('keydown',e=>{if($('birthday').open||['TEXTAREA','INPUT','BUTTON'].includes(document.activeElement.tagName))return;if(e.code==='Space'){e.preventDefault();$('play').click()}if(e.code==='ArrowRight')$('next').click();if(e.code==='ArrowLeft')$('prev').click()});
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});render();
song.onplay=()=>{$('listen').textContent='暫停生日歌曲'};song.onpause=()=>{$('listen').textContent='聽生日歌曲'};song.onended=()=>{$('listen').textContent='再聽一次生日歌曲'};
$('listen').onclick=()=>{if(song.paused){pause();song.muted=false;song.play().catch(()=>toast('請再輕觸一次播放歌曲。'))}else song.pause()};
song.ontimeupdate=()=>{const t=song.currentTime;const cue=(story.lyrics||[]).find(s=>t>=s.start&&t<s.end);$('lyrics').textContent=cue?.text||''};
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'navigate_birthday_chapter',title:'前往生日電影章節',description:'前往指定章節並更新電影畫面；保留目前播放或暫停狀態。',inputSchema:{type:'object',properties:{chapter:{type:'integer',minimum:1,maximum:5}},required:['chapter'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!Number.isInteger(input.chapter)||input.chapter<1||input.chapter>5||Object.keys(input).length!==1)throw new Error('chapter 必須為 1 到 5 的整數');seek(story.chapters[input.chapter-1]);return{chapter:input.chapter,time:film.currentTime,paused:film.paused}}},{signal:lifecycle.signal})).catch(()=>{});addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}catch(e){}}

const gameReturn=new URLSearchParams(location.search);if(gameReturn.get('chapter')==='5'){if(gameReturn.get('gift')==='1'){film.autoplay=false;openGift(false);}film.addEventListener('loadedmetadata',()=>{seek(story.chapters[4]);pause();},{once:true});}
