import * as T from './three.module.js';
const $=id=>document.getElementById(id),keys=new Set(),colors=[0x59a8ff,0xaf85ff,0xff83c8,0x6ee9b6,0xff727e];
let renderer;try{renderer=new T.WebGLRenderer({canvas:$('world'),antialias:true});}catch(e){$('welcome').showModal();$('error').textContent='此裝置暫時無法顯示 3D 世界，請改用其他瀏覽器，或回到電影模式。';$('begin').disabled=true;throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.outputColorSpace=T.SRGBColorSpace;
const scene=new T.Scene();scene.background=new T.Color(0x090e26);scene.fog=new T.FogExp2(0x090e26,.011);const camera=new T.PerspectiveCamera(55,1,.1,180);scene.add(new T.HemisphereLight(0xc9b9ff,0x293756,2.4));const sun=new T.DirectionalLight(0xb9cbff,2.7);sun.position.set(-8,15,10);scene.add(sun);
const materials=new Map();function material(c,glow=false){const key=c+':'+glow;if(!materials.has(key))materials.set(key,new T.MeshStandardMaterial({color:c,roughness:.7,emissive:glow?c:0,emissiveIntensity:glow?.7:0}));return materials.get(key);}
function mesh(parent,geo,c,x,y,z,sx=1,sy=1,sz=1,glow=false){const m=new T.Mesh(geo,material(c,glow));m.position.set(x,y,z);m.scale.set(sx,sy,sz);parent.add(m);return m;}
const box=new T.BoxGeometry(1,1,1),ball=new T.SphereGeometry(1,16,12),cylinder=new T.CylinderGeometry(1,1,1,24);
function person(hair,coat,yiting=false){const g=new T.Group();mesh(g,ball,0xf0c8b8,0,1.91,0,.25,.3,.23);mesh(g,ball,hair,0,2.05,.015,.28,.23,.26);mesh(g,ball,0x252333,-.09,1.94,.214,.026,.031,.016);mesh(g,ball,0x252333,.09,1.94,.214,.026,.031,.016);if(yiting){mesh(g,ball,hair,0,1.58,-.17,.29,.53,.15);mesh(g,ball,0x9299aa,0,2.13,0,.29,.15,.28);mesh(g,box,0x858c9c,0,2.1,.26,.35,.035,.28);}
mesh(g,box,yiting?0x742b43:coat,0,1.36,0,.49,.65,.28);if(yiting){mesh(g,box,coat,-.19,1.38,0,.18,.68,.36);mesh(g,box,coat,.19,1.38,0,.18,.68,.36);mesh(g,box,coat,0,1.4,-.15,.5,.69,.09);}
const arms=[],legs=[];for(const s of [-1,1]){const a=new T.Group();a.position.set(s*.35,1.66,0);mesh(a,box,coat,0,-.26,0,.18,.53,.2);mesh(a,ball,0xf0c8b8,0,-.57,0,.09,.13,.09);g.add(a);arms.push(a);const l=new T.Group();l.position.set(s*.145,1.03,0);mesh(l,box,0x303340,0,-.43,0,.24,.85,.27);mesh(l,box,0xc4c5cf,0,-.94,.08,.26,.12,.42);mesh(l,box,0x343744,0,-.87,.07,.25,.1,.4);if(yiting)mesh(l,box,0x444654,s*.12,-.33,0,.08,.23,.2);g.add(l);legs.push(l);}
g.userData={arms,legs};return g;}
const player=person(0x211f2a,0xb8bfce,true);scene.add(player);player.rotation.y=Math.PI;player.position.set(0,0,8);
mesh(scene,cylinder,0x171e39,0,-.4,-12,26,.6,35);mesh(scene,new T.TorusGeometry(25,.035,6,120),0x726eb7,0,-.06,-12,1,1,1,true).rotation.x=Math.PI/2;
function label(text,color='#e6deff'){const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle=color;ctx.font='32px Microsoft JhengHei, sans-serif';ctx.textAlign='center';ctx.fillText(text,256,75);const tex=new T.CanvasTexture(c);const s=new T.Sprite(new T.SpriteMaterial({map:tex,depthTest:true}));s.scale.set(5,1.25,1);return s;}
const stops=[
{name:'銀虎',place:'10:20 PM｜星光的邀請',x:0,z:1,hair:0xd9e2ec,coat:0x344457,img:'022',text:'YiTing，終於找到妳了。\n別害怕。這次，換我們來接妳。\n跟著星光走，大家都在等妳。',task:'走向藍色星光，與藝俊相遇。'},
{name:'藝俊',place:'音樂花園｜希望',x:-10,z:-7,hair:0x4c83e0,coat:0xdce9ff,img:'card-0000(1)',text:'這一顆，代表希望。\n希望妳不管走到哪裡，都能記得自己最初喜歡的事情。',task:'走向紫色星光，與諾亞相遇。',star:0},
{name:'諾亞',place:'月光溫室｜溫柔',x:10,z:-12,hair:0xe7d297,coat:0x473c66,img:'card-0000(5)',text:'這一顆，代表溫柔。\n有時候，妳也可以不用那麼努力。\n累的時候，就好好休息吧。',task:'走向粉紅色星光，與斑比相遇。',star:1},
{name:'斑比',place:'光之廣場｜快樂',x:-11,z:-23,hair:0xe090b4,coat:0xe9e5f8,img:'card-0000(3)',text:'快快快！這裡超好玩的！\n這一顆代表快樂！\n以後也要像剛剛那樣，多笑一點！',task:'走向綠色星光，與河玟相遇。',star:2},
{name:'河玟',place:'星海觀景台｜勇氣',x:11,z:-30,hair:0x222a36,coat:0x344c47,img:'card-0000(4)',text:'妳看那裡。雖然它很小，但還是一直在發光。\n這一顆，代表勇氣。\n就算現在還看不見終點，也沒關係。只要繼續往前走就好了。',task:'走向紅色星光，聽銀虎想對妳說的話。',star:3},
{name:'銀虎',place:'安靜的星光步道｜陪伴',x:0,z:-39,hair:0xd9e2ec,coat:0x344457,img:'026',text:'所以今天，我也想把一點力量送給妳。\n這一顆，代表陪伴。\n希望妳都不要忘記，自己也是很重要的人。\n真正的驚喜，還沒開始。',task:'五顆星光已集齊！走向只為妳亮起的舞台。',star:4},
{name:'PLAVE',place:'只為妳亮起的舞台',x:0,z:-49,img:'020',text:'YiTing，生日快樂！\n今天，也是這個世界上，多了一個妳的日子。\n所以今晚，這首歌只送給妳。\n把願望交給星光，妳值得被好好慶祝。',task:'星光旅程完成。回到電影，收下這份生日祝福。'}];
const lanterns=[];stops.forEach((s,i)=>{const color=colors[s.star??4];mesh(scene,cylinder,0x25304c,s.x,-.05,s.z,3.2,.16,3.2);const ring=mesh(scene,new T.TorusGeometry(2.6,.055,8,64),color,s.x,.07,s.z,1,1,1,true);ring.rotation.x=Math.PI/2;if(i<6){const p=person(s.hair,s.coat);p.position.set(s.x,0,s.z);scene.add(p);s.actor=p;}const sign=label(s.name+' · '+(i===0?'邀請':i===6?'生日舞台':['希望','溫柔','快樂','勇氣','陪伴'][s.star]));sign.position.set(s.x,3.3,s.z);scene.add(sign);s.sign=sign;const star=mesh(scene,new T.OctahedronGeometry(.28),color,s.x,2.9,s.z+.9,1,1,1,true);lanterns.push(star);});
// A dotted route links the same encounters as the novel.
let last={x:0,z:8};stops.forEach(s=>{const d=Math.hypot(s.x-last.x,s.z-last.z);for(let i=0;i<d;i+=1.1){const f=i/d;mesh(scene,ball,0x8579ba,last.x+(s.x-last.x)*f,.04,last.z+(s.z-last.z)*f,.055,.035,.055,true);}last=s;});
for(let i=0;i<90;i++){const a=i*2.399,r=29+(i%9)*3,x=Math.cos(a)*r,z=Math.sin(a)*r-14;if(Math.abs(x)<24&&z>-58&&z<16)continue;mesh(scene,box,0x172445,x,1+(i%7),z,1.2,2+(i%8)*1.6,1.2);}
for(let i=0;i<36;i++){const a=i*2.399,r=5+(i%5)*3;const f=mesh(scene,new T.IcosahedronGeometry(.36),colors[i%5],-10+Math.cos(a)*r,.3,-7+Math.sin(a)*r,1,1.2,1,true);f.rotation.z=a;}
mesh(scene,cylinder,0x302647,0,.14,-49,5,.4,4);const arch=mesh(scene,new T.TorusGeometry(4,.14,8,64,Math.PI),0xb49aff,0,1,-50,1,1,1,true);for(let i=0;i<5;i++){const p=person([0x4c83e0,0xe7d297,0xe090b4,0xd9e2ec,0x222a36][i],0xeeeaf8);p.position.set((i-2)*1.5,.35,-51);scene.add(p);}
const vertices=[];for(let i=0;i<1000;i++)vertices.push((Math.random()-.5)*160,6+Math.random()*65,(Math.random()-.5)*150-25);const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(vertices,3));scene.add(new T.Points(geo,new T.PointsMaterial({color:0xcac0ff,size:.09})));
let step=0,collected=[],started=false,paused=false,yaw=0,drag=null,walk=0,lastTime=performance.now(),near=false,autoWalk=false;
try{const save=JSON.parse(localStorage.getItem('yiting-starlight-game-v1'));if(save&&Number.isInteger(save.step)&&save.step>=0&&save.step<=7){step=save.step;collected=stops.slice(0,step).filter(s=>s.star!==undefined).map(s=>s.star);const s=stops[Math.min(step,6)];player.position.set(s.x,0,s.z+5);}}catch{}
function updateHUD(){const target=stops[Math.min(step,6)];$('task').textContent=step===7?stops[6].task:step===0?'走向銀虎，接受今晚的邀請。':stops[step-1].task;$('stars').replaceChildren();colors.forEach((c,i)=>{const el=document.createElement('span');el.className='star'+(collected.includes(i)?' found':'');el.style.color='#'+c.toString(16).padStart(6,'0');el.textContent='✦';el.title=['希望','溫柔','快樂','勇氣','陪伴'][i];$('stars').append(el);});lanterns.forEach((l,i)=>{l.visible=i>=step;stops[i].sign.visible=i>=step;});}
function interact(){if(!near||paused||!started||$('conversation').open)return;keys.clear();autoWalk=false;$('route').textContent='沿星光前往';const s=stops[Math.min(step,6)];$('portrait').src=`assets/${s.img}.webp`;$('portrait').alt=s.name+'與 YiTing 的生日相遇';$('name').textContent=s.name;$('place').textContent=s.place;$('words').textContent=s.text;$('filmLink').hidden=step<6;$('continue').textContent=step>=6?'留在星光世界':step===0?'接受邀請，走進星光':'收下星光，繼續旅程';$('conversation').showModal();}
$('route').onclick=()=>{autoWalk=!autoWalk;$('route').textContent=autoWalk?'停止引導':'沿星光前往';};$('restart').onclick=()=>{step=0;collected=[];player.position.set(0,0,8);player.rotation.y=Math.PI;try{localStorage.removeItem('yiting-starlight-game-v1');}catch{}updateHUD();};$('talk').onclick=interact;$('continue').onclick=()=>{if(step<7){const s=stops[step];if(s.star!==undefined&&!collected.includes(s.star))collected.push(s.star);step++;try{localStorage.setItem('yiting-starlight-game-v1',JSON.stringify({step}));}catch{}updateHUD();}$('conversation').close();};$('conversation').addEventListener('cancel',e=>e.preventDefault());
$('begin').onclick=()=>{started=true;$('welcome').close();lastTime=performance.now();};$('welcome').showModal();
function togglePause(){paused=!paused;keys.clear();$('pause').textContent=paused?'繼續':'暫停';if(paused)$('bgm').pause();} $('pause').onclick=togglePause;
$('music').onclick=()=>{const a=$('bgm');if(a.paused)a.play().then(()=>$('music').textContent='關閉音樂').catch(()=>$('music').textContent='再點一次播放');else{a.pause();$('music').textContent='開啟音樂';}};
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();if(e.repeat)return;if(e.key.toLowerCase()==='e')interact();else if(e.key.toLowerCase()==='p'&&started&&!$('conversation').open)togglePause();else keys.add(e.key.toLowerCase());});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key.toLowerCase());};for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>keys.delete(b.dataset.key.toLowerCase()));});
$('world').onpointerdown=e=>{drag={id:e.pointerId,x:e.clientX};$('world').setPointerCapture(e.pointerId);};$('world').onpointermove=e=>{if(drag&&drag.id===e.pointerId){yaw-=(e.clientX-drag.x)*.006;drag.x=e.clientX;}};for(const ev of ['pointerup','pointercancel'])$('world').addEventListener(ev,()=>drag=null);
addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>{keys.clear();if(document.hidden&&started&&!paused)togglePause();});
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}addEventListener('resize',resize);resize();updateHUD();
function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-lastTime)/1000,.05);lastTime=now;const moving=started&&!paused&&!$('conversation').open&&!document.hidden;let x=0,z=0;if(moving){x=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0);z=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);if(x||z){autoWalk=false;$('route').textContent='沿星光前往';}if(autoWalk){const target=stops[Math.min(step,6)],dx=target.x-player.position.x,dz=target.z-player.position.z,d=Math.hypot(dx,dz);if(d<2.3){autoWalk=false;$('route').textContent='沿星光前往';}else{x=(dx*Math.cos(yaw)-dz*Math.sin(yaw))/d;z=(dz*Math.cos(yaw)+dx*Math.sin(yaw))/d;}}const len=Math.hypot(x,z);if(len){x/=len;z/=len;const dx=x*Math.cos(yaw)+z*Math.sin(yaw),dz=z*Math.cos(yaw)-x*Math.sin(yaw);player.position.x=T.MathUtils.clamp(player.position.x+dx*5*dt,-21,21);player.position.z=T.MathUtils.clamp(player.position.z+dz*5*dt,-54,13);player.rotation.y=Math.atan2(dx,dz);walk+=dt*9;}player.userData.legs.forEach((l,i)=>l.rotation.x=len?Math.sin(walk+i*Math.PI)*.45:0);player.userData.arms.forEach((l,i)=>l.rotation.x=len?-Math.sin(walk+i*Math.PI)*.3:0);}
const target=stops[Math.min(step,6)],distance=Math.hypot(player.position.x-target.x,player.position.z-target.z);near=distance<3.2;const disabled=!near||paused;if($('talk').disabled!==disabled)$('talk').disabled=disabled;const talkLabel=near?'與 '+target.name+' 交談':'靠近 '+target.name;if($('talk').textContent!==talkLabel)$('talk').textContent=talkLabel;$('distance').textContent=paused?'旅程已暫停':step===7?'五道星光，一個只屬於妳的夜晚。':target.name+' · '+Math.round(distance)+' 公尺';
const cp=new T.Vector3(player.position.x+Math.sin(yaw)*7,player.position.y+4.4,player.position.z+Math.cos(yaw)*7);camera.position.lerp(cp,1-Math.exp(-dt*6));camera.lookAt(player.position.x,1.4,player.position.z);lanterns.forEach((l,i)=>{l.rotation.y=now*.001;l.position.y=2.9+Math.sin(now*.0015+i)*.12;});renderer.render(scene,camera);}
camera.position.set(0,4.4,15);requestAnimationFrame(frame);
