const byId=id=>document.getElementById(id),chapters=window.NOVEL_TEXT,panels=window.NOVEL_PANELS;
const music=byId('comicMusic'),tracks=['assets/ten-twenty-star.m4a','assets/song.m4a','assets/moon-night.m4a'];let track=0,userPaused=false,chapter=0;
const starNames={blue:'希望',purple:'溫柔',pink:'快樂',green:'勇氣',red:'陪伴'},colors={blue:'#69b9ff',purple:'#b58aff',pink:'#ef8eb7',green:'#83bf83',red:'#ed7185'};let collected=[];
try{collected=JSON.parse(localStorage.getItem('yiting-novel-comic-stars')||'[]');if(!Array.isArray(collected))collected=[];}catch{}
function syncMusic(){const save=byId('downloadSong'),title=['열 시 이십 분의 별','너라는_별빛','10월의 밤'][track];save.href=tracks[track];save.download=title+'.m4a';save.textContent='下載 '+title+' ↓';byId('musicToggle').textContent=music.paused?(userPaused?'播放音樂':'音樂開啟 · 輕觸播放'):'暫停音樂';byId('musicToggle').setAttribute('aria-pressed',String(!userPaused));document.querySelectorAll('[data-track]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.track)===track)));}
function play(){music.muted=false;music.play().then(()=>{byId('musicStatus').textContent='正在播放：'+['열 시 이십 분의 별','너라는_별빛','10월의 밤'][track];}).catch(()=>{byId('musicStatus').textContent='輕觸播放，讓音樂陪妳讀故事。';syncMusic();});}
music.onplay=syncMusic;music.onpause=syncMusic;music.onended=()=>{track=(track+1)%tracks.length;music.src=tracks[track];syncMusic();play();};
byId('musicToggle').onclick=()=>{if(music.paused){userPaused=false;play();}else{userPaused=true;music.pause();byId('musicStatus').textContent='音樂已暫停';}};
document.querySelectorAll('[data-track]').forEach(button=>button.onclick=()=>{track=Number(button.dataset.track);music.src=tracks[track];userPaused=false;syncMusic();play();});
document.addEventListener('visibilitychange',()=>{if(document.hidden)music.pause();});
chapters.forEach((c,i)=>{const o=document.createElement('option');o.value=i;o.textContent=c.title;byId('chapterSelect').append(o);});
function starStatus(){byId('starStatus').textContent=collected.length?'已收藏 '+collected.filter(c=>starNames[c]).map(c=>starNames[c]).join('、')+' 星光。':'輕觸星光按鈕，收藏五份心意。';}
function download(img){return 'assets/downloads/'+img+'.jpg';}
function render(index,scroll=true){chapter=Math.max(0,Math.min(chapters.length-1,index));byId('chapterSelect').value=chapter;byId('chapterTitle').textContent=chapters[chapter].title;byId('chapterNumber').textContent='CHAPTER '+String(chapter+1).padStart(2,'0');byId('chapterProgress').textContent='YITING / THE NOVEL COMIC';byId('pageCount').textContent=(chapter+1)+' / '+chapters.length;byId('prev').disabled=chapter===0;byId('next').disabled=chapter===chapters.length-1;byId('finish').hidden=chapter!==chapters.length-1;byId('original').open=false;byId('originalText').replaceChildren();chapters[chapter].paragraphs.forEach(text=>{const p=document.createElement('p');p.textContent=text;byId('originalText').append(p);});byId('panels').replaceChildren();byId('panels').classList.toggle('star-quest',chapter===4);
 panels[chapter].forEach(([img,narration,lines,star],i)=>{const panel=document.createElement('section');panel.className='panel';if(chapter===4){panel.dataset.member=img.includes('yejun')||img==='novel-garden'?'blue':img.includes('noah')||img==='novel-greenhouse'||img==='novel-greenhouse-wide'||img==='novel-purple-star-detail'?'purple':img.includes('bamby')?'pink':'green';if(img==='novel-yejun-guitar'||img==='novel-bamby-dance'||img==='novel-greenhouse-wide'||img==='novel-observatory-wide')panel.classList.add('scene-opening');}const number=document.createElement('span');number.className='panel-number';number.textContent=String(i+1).padStart(2,'0');const art=document.createElement('button');art.type='button';art.className='art-button';art.setAttribute('aria-label','放大查看：'+narration);const image=document.createElement('img');image.src='assets/'+img+'.webp';image.alt=narration;image.loading=i===0?'eager':'lazy';art.append(image);art.onclick=()=>{byId('imageTitle').textContent=chapters[chapter].title;byId('largeImage').src=image.src;byId('largeImage').alt=narration;byId('saveImage').href=download(img);byId('saveImage').download=img+'.jpg';byId('imageViewer').showModal();};const copy=document.createElement('div');copy.className='panel-copy';const caption=document.createElement('p');caption.className='narration';caption.textContent=narration;copy.append(caption);lines.forEach(([who,text])=>{const bubble=document.createElement('div');bubble.className='bubble';const name=document.createElement('strong');name.textContent=who;const line=document.createElement('p');line.textContent=text;bubble.append(name,line);copy.append(bubble);});const tools=document.createElement('div');tools.className='panel-tools';const save=document.createElement('a');save.href=download(img);save.download=img+'.jpg';save.textContent='保存這格插畫 ↓';tools.append(save);if(star){const button=document.createElement('button');button.className='star-button';button.style.setProperty('--star-color',colors[star]);button.setAttribute('aria-pressed',String(collected.includes(star)));button.innerHTML='<span>✦</span> '+(collected.includes(star)?'已收藏':'收藏')+starNames[star]+'星光';button.onclick=()=>{if(!collected.includes(star))collected.push(star);try{localStorage.setItem('yiting-novel-comic-stars',JSON.stringify(collected));}catch{}button.setAttribute('aria-pressed','true');button.innerHTML='<span>✦</span> 已收藏'+starNames[star]+'星光';starStatus();};tools.append(button);}copy.append(tools);panel.append(number,art,copy);byId('panels').append(panel);});
 byId('starStatus').hidden=chapter!==4&&chapter!==5;starStatus();try{history.replaceState(null,'','#chapter-'+chapter);localStorage.setItem('yiting-novel-comic-page',String(chapter));}catch{}window.refreshComicAtmosphere?.(chapter);if(scroll){byId('chapterTitle').scrollIntoView({block:'start'});}if(!userPaused&&music.paused)play();}
byId('chapterSelect').onchange=e=>render(Number(e.target.value));byId('prev').onclick=()=>render(chapter-1);byId('next').onclick=()=>render(chapter+1);byId('closeViewer').onclick=()=>byId('imageViewer').close();
document.addEventListener('keydown',e=>{if(byId('imageViewer').open||['INPUT','SELECT','TEXTAREA','BUTTON'].includes(document.activeElement.tagName))return;if(e.key==='ArrowRight'&&chapter<9){e.preventDefault();render(chapter+1);}if(e.key==='ArrowLeft'&&chapter>0){e.preventDefault();render(chapter-1);}});
let initial=0;const match=/^#chapter-(\d+)$/.exec(location.hash);if(match)initial=Number(match[1]);else try{initial=Number(localStorage.getItem('yiting-novel-comic-page')||0);}catch{}if(!Number.isFinite(initial))initial=0;render(initial,false);syncMusic();
